version: "3.9"
services:
  asset:
    build: .
    container_name: asset-manager
    ports:
      - "3000:3000"
    volumes:
     - ./data:/app/data                    # 挂载整个数据目录 (data.json + uploads)